name: "Build site"
description: "Build an IRIS-HEP style website. INDICO keys should be set, and rake should be supported."
inputs:
  ruby-version:
    description: "Version of ruby to prepare"
    required: false
    default: "3.3"

runs:
  using: composite
  steps:
    - name: Restore publication cache
      uses: actions/cache@v4
      with:
        path: _cache
        key: ${{ runner.os }}-_cache-${{ hashFiles('_data/publications/*.yml') }}

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-cache: true
